- name: Update apt cache
  action: apt update_cache=yes

- name: Install dependencies
  action: apt pkg={{item}} state=latest
  with_items:
    - libcurl4-openssl-dev
    - curl
    - git
    - make
    - nodejs
    - python
    - python-pycurl
    - python-psycopg2
    - python-software-properties
    - libpq-dev
    - libjpeg-dev

- name: Place s3_put.sh in PATH
  sudo: yes
  copy:
    mode: 0755
    owner: vagrant
    group: vagrant
    src: s3_put.sh
    dest: /usr/local/bin/s3_put.sh